web:
  build: .
  command: python -u app.py
  ports:
    - "5000:5000"
  volumes:
    - .:/app
  links:
    - db
  environment: 
    DB_HOST: db
    DB_USER: ${DB_USER}
    DB_PASSWORD: ${DB_PASSWORD}
    DB_NAME: ${DB_NAME}
db:
  image: mysql
  restart: always
  command: --default-authentication-plugin=mysql_native_password
  environment:
    MYSQL_USER: ${DB_USER}
    MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    MYSQL_DATABASE: ${DB_NAME}
  ports:
    - 3306:3306
  volumes: 
    - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql


  